main()
{
    printf("Hello\tworld");
    printf("\nHello\bworld");
    printf("\nHello\rworld");
    printf("\nHello\\world");
    printf("\nHello\"world");
    printf("\nHello\'world");
    getch();
}
